### ISSUE TITLE
Numbering of FC and GML schema

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-129-Product-Specification#11]
The version/edition numbers in the XML FC and GML schema must be consistent with the _Edition.Revision_ component for the corresponding Product Specification. FC edition 1.2.0 implies it is the feature catalogue for S-129 PS Edition 1.2.0. Similarly for the GML schema.

Apparently the current (as of 19 May 2024) FC and GML schema still correspond to S-129 Ed. 1.1.0, so their internal edition/version numbers (and the file names, if they include the edition number) should be corrected. Since there already exist released FC and XSD files with 1.1.0 numbering, the new files **for S-129 Ed. 1.1.0** must be distinguishable from prior releases and use 1.1.1 or 1.1.1-YYYYMMDD. The alternative is to move everything (PS, FC, GML schema) to Edition 1.2.0 concurrently.

**Comment by jrhee01** [comment]
thanks @rmalyankar. I have added a copy of your XSD version 1.1.1 under the 1.1.0 folder.
Ultimately, yes, everything should be moved to 1.2.0 altogether.
