### ISSUE TITLE
Update Feature Catalogue and UML Diagrams for Enhanced Association and Enumeration Definitions

### ISSUE THREAD

**Issue by KMOUSQA** [iho-ohi/S-129-Product-Specification#13]
# **Details of Changes:**

### **1. Feature Catalogue Modifications:**

**Association Definition**
Define the roles "Component of" and "Consists of" used in our UML to specify the relationship between features (Feature Association). This will involve creating a list defining these roles and naming each association.

**List Associations**
Further define the relationships between features by listing them. This list will help in visualizing the interactions and dependencies among features.

**Multiplicity Definition**
Specify the multiplicity in relationships where a feature is defined in relation to another feature.

### **2. UML Diagram Modifications:**

![KakaoTalk_20240623_124820112](https://github.com/iho-ohi/S-129-Product-Specification/assets/11741132/495e47f8-4250-4a36-8110-ae76796b329f)

**Enumeration Updates**
Document missing enumeration numbers in the Enumeration type to ensure consistency and completeness.

**Association Removal**
Remove the existing associations between Enumeration, ComplexAttribute, and Feature as specified in the modifications of the Feature Catalogue.

**Multiplicity Documentation**
Based on the updated Feature Catalogue, document the multiplicity of attributes to align with our model's structural requirements.

**Additional Notes**

Both the naming of associations in the Feature Catalogue and certain elements in the UML diagrams may require further modifications pending discussions in upcoming meetings.

**Revised Feature Catalogue**
[S-129_1_2_0_FC_240620.zip](https://github.com/user-attachments/files/15942454/S-129_1_2_0_FC_240620.zip)

**Comment by jrhee01** [comment]
Thanks @KMOUSQA for raising this issue.
I have committed the following changes on branch "**_13-update-feature-catalogue-and-uml-diagrams-for-enhanced-association-and-enumeration-definitions_**":

1. @KMOUSQA's FC changes to as per issue raised
2. Added constraints to "_maximumDraught_", "_expectedPassingSpeed_", and "_distanceAboveUKCLimit_" attributes
3. Corrected feature camelCases - first letter uppercase, consistent with IHO GI Registry's Data Dictionary Register
4. Cleaned up indentation of rows corresponding to uom attribute
5. Cleaned up FC filenames and version numbers/dates to improve visibility to version tracking
6. _(not related to this issue; changed test dataset file names to better conform to naming convention)_

@rmalyankar, @KMOUSQA, much appreciated if you could review all the changes committed on branch.
Please feel free to make updates/corrections as necessary.

**Comment by jrhee01** [comment]
Updated UML diagrams - 2 veresions: 1 with UnderKeelClearancePlanArea, 1 without.

![PlanArea](https://github.com/iho-ohi/S-129-Product-Specification/assets/144688544/d15ddb92-a7d4-4f4b-b509-2a0edabf80dd)
![WithoutPlanArea](https://github.com/iho-ohi/S-129-Product-Specification/assets/144688544/a7ebea6b-ae44-412d-a243-a3f259e424e4)

**Comment by jrhee01** [comment]
In summary, following changes have been made and merged into the main branch:

- feature relationships (aggregations) included in FC and UML diagram of PS
- enumeration numbers included in UML diagram of PS

Additionally, following FC changes were made on this branch:

- _UnderKeelClearancPlanArea_ feature added
- Constraints, namely lower bounds, have been added to numerical attributes -  "_maximumDraught_", "_expectedPassingSpeed_", and "_distanceAboveUKCLimit_"
- Updated _UnderKeelClearancePlan_ from MetaFeatureType to FeatureType. Use type also updated from "meta" to "geographic", while _permittedPrimitive_ amended to noGeometry

Some PC changes were also made on this branch:

- UnderKeelClearanceAlmostNonNavigableArea colour to GOLDN
- Aymbol and linestyles renamed for portraying UnderKeelClearancaControlPoint and UnderKeelClearancePlanArea, to match submissions to IHO GI Registry
- Minor adjustments to symbol for UnderKeelClearancaControlPoint
