### ISSUE TITLE
GML schema version

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-129-Product-Specification#3]
- The _version_ attribute in the 1.1.0 GML schema is "1.0-20231103". 
- The comment in the XSD file says nothing about it being updated for Edition 1.1.0.
- The name of the XSD file (S129_1_1_0.xsd) suggests it is for Edition 1.1.0 
- AFAICS from the GI registry, November 2023 is when Edition 1.1.0 was published. 

These contradictions should be resolved. The GML schema version and internal comments should correspond to the edition number of the product specification on which it is based.

**Comment by jrhee01** [comment]
Version correction in the XSD file has been committed on "3-gml-schema-version" branch .
I have created the following pull request:
"https://github.com/iho-ohi/S-129-Product-Specification/pull/5/commits"

@rmalyankar, unfortunately I don't have the permissions to add you as a reviewer for my pull request. But much appreciated if you could review the commit above, and advise me on whether you're happy with the change. Thanks.
