### ISSUE TITLE
FC 1.1.0 misspelled attribute "Scale Mimimum"

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-129-Product-Specification#6]
The 1.1 FC contains a misspelled (and superfluous) simple attribute "Scale Mimimum" (code _scaleMimimum_).

**Comment by jrhee01** [comment]
Thanks @rmalyankar. Have committed a change on the "4-gml-schema-compliance-to-s-100-5x" branch to fix the misspelling.
